[tool.ruff]
# Target Python 3.9
target-version = "py39"

# Same as Black line length
line-length = 100

# Exclude directories
exclude = [".git", "__pycache__", ".pytype", "build", "dist", "custom_pattern"]

[tool.ruff.lint]
# Enable common linting rules
select = [
    "E",   # pycodestyle errors
    "W",   # pycodestyle warnings
    "F",   # pyflakes
    "UP",  # pyupgrade
    "B",   # flake8-bugbear
    "SIM", # flake8-simplify
    "I",   # isort
]

# Ignore specific rules
ignore = [
    "E501",   # line too long (handled by formatter)
    "E731",   # lambda assignment
    "B008",   # function calls in argument defaults
    "SIM108", # Use ternary operator
]

# Allow unused variables when underscore-prefixed
dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"

[tool.ruff.lint.per-file-ignores]
"__init__.py" = ["F401"] # Allow unused imports in __init__ files

[tool.ruff.lint.isort]
known-first-party = ["audio", "contact"]

[tool.ruff.format]
# Use double quotes for strings
quote-style = "double"

# Indent with spaces
indent-style = "space"

# Unix line endings
line-ending = "lf"
